### ISSUE TITLE
HELP: Reading Kepware OPC-UA Server

### ISSUE THREAD

**Issue by charlyjna** [vogler75/automation-gateway#6]
Hi,

This 'issue' is mainly for asking some help about how to read a topic from Kepware OPC-UA Server. I created a very simple _config.yaml_ file:
```yaml
Servers:
  Mqtt:
    - Id: Mqtt
      Port: 1883
      Host: 0.0.0.0

  OpcUa:
    - Port: 4000
      Path: server
      Topics:
        - Topic: opc/my_opc_id/Root/Objects/Machine1/PLC/#

Drivers:
  OpcUa:
    - Id: my_opc_id
      EndpointUrl: "opc.tcp://192.168.10.11:49320/Kepware.KEPServerEX.V6"
      UpdateEndpointUrl: true
      SecurityPolicy: None
```

Unfortunately, I cannot see anything using UAExpert Client. But, with UAExpert Client, I double checked that I have tags in path:
<pre>
Root
  |- Objects
      |- Machine1
          |- PLC
              |- Type (INT16)
              |- Temp (FLOAT)
</pre>

Moreover, regarding container logs, I do not have any error. The OpcUaClient driver is connected to Kepware Server, I am able to connect to Frankestein OPC-UA server or MQTT server.

Am I missing something?

Thank you.

Charly
