### ISSUE TITLE
Influxdb v2

### ISSUE THREAD

**Issue by tobias-carlbom** [vogler75/automation-gateway#7]
Hi,

I am truly amazed but this project! Awesome work :)

Is influxdb version 2 supported? I have not found any in the example config files :/

**Comment by vogler75** [comment]
Good point, to be honest I haven't yet used 2.x. InfluxDB changed a lot in between version. Need to test it.

**Comment by vogler75** [comment]
Database: use the "Bucket" name which you have created in Influx.  
Username: seems to be not used, but it must not be empty!  
Password: use the Token which you have created in Influx.  

```
  InfluxDB:
    - Id: influx
      Url: http://linux0.rocworks.local:8086
      Database: Rocworks
      Username: "-"
      Password: "7a2HbAPcWSHNQP8Z7sxnjRlTrOCJxuoNoNJlY-23Fu2pT81sTjfijelwjoQKKQz31taWLSKUXFU4-sHaTFBmLA=="
      Logging:
        - Topic: opc/demo1/path/Objects/Dynamic/#
```
